// // export const ingredientsList = [
// //     { label: 'Vodka' },
// //     { label: 'Rum' },
// //     { label: 'Tequila' },
// //     { label: 'Whiskey' },
// //     { label: 'Cranberry Juice' },
// //     { label: 'Redbull' },
// //     { label: 'Orange Juice' },
// //     { label: 'Gin' },
// //   ];


// const mockData = {
//   cardData: [
//     {id:1, 
//       label:'Vodka',
//       img:'',
//       description:'Add 2 cups of vodka',

//     },
//     {id:2, 
//       label:'Tequila',
//       img:'',
//       description:'Add 2 cups of Taquila',

//     },
//     {id:3, 
//       label:'Rum',
//       img:'',
//       description:'Add 2 cups of rum',

//     },

//     // {id:4, 
//     //   label:'Vodka',
//     //   img:img1,
//     //   description:'Add 2 cups of vodka',

//     // },
//     // {id:5, 
//     //   label:'Tequila',
//     //   img:img2,
//     //   description:'Add 2 cups of Taquila',

//     // },
//     // {id:6, 
//     //   label:'Rum',
//     //   img:img3,
//     //   description:'Add 2 cups of rum',

//     // },
//   ]

// }
// export default mockData;
export const ingredientsList = [
  { label: 'Creme de Cacao'},
  { label: 'Absolut Kurant'},
  { label: 'Lager'},
  { label: 'Malibu rum'},
  { label: 'Dark rum'},
  { label: 'Goldschlager'},
  { label: '151 proof rum'},
  { label: 'Jack Daniels'},
  { label: 'Gin'},
  { label: 'Peach Vodka'},
  { label: 'Vanilla vodka'},
  { label: 'Blue Curacao'},
  { label: 'Kahlua'},
  { label: 'Absolut Citron'},
  { label: 'Coconut rum'},
  { label: 'Light rum'},
  { label: 'Vodka'},
  { label: 'Amaretto'},
  { label: 'Cranberry juice'},
  { label: 'Applejack'},
  { label: 'White Creme de Menthe'},
  { label: 'Absolut Vodka'},
  { label: 'Rum'},
  { label: 'Sweet Vermouth'},
  { label: 'Strawberry schnapps'},
  { label: 'Scotch'},
  { label: 'Apricot brandy'},
  { label: 'Peppermint schnapps'},
  { label: 'Triple sec'},
  { label: 'Grenadine'},
  { label: 'Southern Comfort'},
  { label: 'Orange bitters'},
  { label: 'Lemon vodka'},
  { label: 'Blended whiskey'},
  { label: 'Dry Vermouth'},
  { label: 'Water'},
  { label: 'Sugar'},
  { label: 'Chocolate ice-cream'},
  { label: 'Sour mix'},
  { label: 'Tea'},
  { label: 'Campari'},
  { label: 'Angelica root'},
  { label: 'Orange juice'},
  { label: 'Berries'},
  { label: 'Apple cider'},
  { label: 'Tequila'},
  { label: 'Apple juice'},
  { label: '7-Up'},
  { label: 'Maui'},
  { label: 'Champagne'},
  { label: 'Lemonade'},
  { label: 'Jaegermeister'},
  { label: 'Crown Royal'},
  { label: "Bailey's irish cream"},
  { label: 'Cantaloupe'},
  { label: 'Milk'},
  { label: 'Strawberries'},
  { label: 'Ice'},
  { label: 'Brandy'},
  { label: 'Everclear'},
  { label: 'Irish cream'},
  { label: 'Ale'},
  { label: 'Coffee liqueur'},
  { label: 'Guinness stout'},
  { label: 'Aanejo rum'},
  { label: 'Midori melon liqueur'},
  { label: 'Vanilla Ice-Cream'},
  { label: 'Pineapple juice'},
  { label: 'Bourbon'},
  { label: 'Sambuca'},
  { label: 'Corona'},
  { label: 'Coffee'},
  { label: 'Lime'},
  { label: 'Orange'},
  { label: 'Cocoa powder'},
  { label: 'Chocolate'},
  { label: 'Chocolate liqueur'},
  { label: 'Banana liqueur'},
  { label: 'Bacardi Limon'},
  { label: 'Bitters'},
  { label: 'Coca-Cola'},
  { label: 'Cointreau'},
  { label: 'Cranberries'},
  { label: 'Spiced rum'},
  { label: 'Whiskey'},
  { label: 'demerara Sugar'},
  { label: 'Cherry Heering'},
  { label: 'Fruit punch'},
  { label: 'Heavy cream'},
  { label: 'Dubonnet Rouge'},
  { label: 'Pisco'},
  { label: 'Chocolate syrup'},
  { label: 'Egg yolk'},
  { label: 'Egg'},
  { label: 'Firewater'},
  { label: 'Cognac'},
  { label: 'Yoghurt'},
  { label: 'Galliano'},
  { label: 'Lime juice'},
  { label: 'Cachaca'},
  { label: 'Red wine'},
  { label: 'Grapes'},
  { label: 'Green Creme de Menthe'},
  { label: 'Cider'},
  { label: 'Whisky'},
  { label: 'Hot Damn'},
  { label: 'Grape juice'},
  { label: 'Lemon peel'},
  { label: 'Irish whiskey'},
  { label: 'Apple brandy'},
  { label: 'Baileys irish cream'},
  { label: 'Blackberry brandy'},
  { label: 'Ginger'},
  { label: 'Creme de Cassis'},
  { label: 'Cranberry vodka'},
  { label: 'Kiwi liqueur'},
  { label: 'Kiwi'},
  { label: 'Kool-Aid'},
  { label: 'Mango'},
  { label: 'Carbonated water'},
  { label: 'Beer'},
  { label: 'Espresso'},
  { label: 'Mint'},
  { label: 'Absinthe'},
  { label: 'Cherry brandy'},
  { label: 'Lemon juice'},
  { label: 'Sprite'},
  { label: 'Port'},
  { label: 'Coffee brandy'},
  { label: 'Black Sambuca'},
  { label: 'Sugar syrup'},
  { label: 'Raspberry vodka'},
  { label: 'Frangelico'},
  { label: 'Grapefruit juice'},
  { label: 'Ricard'},
  { label: 'Johnnie Walker'},
  { label: 'Sherry'},
  { label: 'Jim Beam'},
  { label: 'Sloe gin'},
  { label: 'Advocaat'},
  { label: 'Peach nectar'},
  { label: 'Prosecco'},
  { label: 'Lemon'},
  { label: 'Ouzo'},
  { label: 'Godiva liqueur'},
  { label: 'Grand Marnier'},
  { label: 'Yukon Jack'},
  { label: 'Tomato juice'},
  { label: 'Wild Turkey'},
  { label: 'White Rum'},
  { label: 'Vermouth'},
  { label: 'Zima'},
  { label: 'Peachtree schnapps'},
  { label: 'Chambord raspberry liqueur'},
  { label: 'Food coloring'},
  { label: 'Glycerine'},
  { label: 'Nutmeg'},
  { label: 'Blueberry schnapps'},
  { label: 'Orange Curacao'},
  { label: 'Ginger beer'},
  { label: 'Peach schnapps'},
  { label: 'Soda water'},
  { label: 'Kirschwasser'},
  { label: 'Pisang Ambon'},
  { label: 'Sweet and sour'},
  { label: 'Creme de Banane'},
  { label: 'Dark Creme de Cacao'},
  { label: 'Light cream'},
  { label: 'Almond'},
  { label: 'Apple'},
  { label: 'Brown sugar'},
  { label: 'Carrot'},
  { label: 'Apple schnapps'},
  { label: 'Wine'},
  { label: 'Grape soda'},
  { label: 'Mountain Dew'},
  { label: 'Iced tea'},
  { label: 'Rye whiskey'},
  { label: 'Banana'},
  { label: 'Coconut liqueur'},
  { label: 'Root beer'},
  { label: 'Tia maria'},
  { label: 'Passion fruit juice'},
  { label: 'Erin Cream'},
  { label: 'Club soda'},
  { label: 'Tabasco sauce'},
  { label: 'Butterscotch schnapps'},
  { label: 'Maraschino liqueur'},
  { label: 'Vanilla extract'},
  { label: 'Ginger ale'},
  { label: 'Peach Bitters'},
  { label: 'Absolut Peppar'},
  { label: 'Sarsaparilla'},
  { label: 'Raspberry Liqueur'},
  { label: 'Benedictine'},
  { label: 'Pineapple'},
  { label: 'Fruit juice'},
  { label: 'Tonic water'},
  { label: 'Carbonated soft drink'},
  { label: 'Corn syrup'},
  { label: 'Butter'},
  { label: 'Half-and-half'},
  { label: 'Peach brandy'},
  { label: 'Tennessee whiskey'},
  { label: 'Jello'},
  { label: 'Anis'},
  { label: 'Green Chartreuse'},
  { label: 'Grain alcohol'},
  { label: 'Apfelkorn'},
  { label: 'Bitter lemon'},
  { label: 'Papaya'},
  { label: 'Drambuie'},
  { label: 'Orgeat syrup'},
  { label: 'Tropicana'},
  { label: 'Honey'},
  { label: 'Pina colada mix'},
  { label: 'Angostura bitters'},
  { label: 'Coconut milk'},
  { label: 'Pink lemonade'},
  { label: 'Cherry liqueur'},
  { label: 'Lime vodka'},
  { label: 'Lemon-lime soda'},
  { label: 'Powdered sugar'},
  { label: 'Anisette'},
  { label: 'Cinnamon'},
  { label: 'Aquavit'},
  { label: 'Coriander'},
  { label: 'Maple syrup'},
  { label: 'Schweppes Russchian'},
  { label: 'Fruit'},
  { label: 'Surge'},
  { label: 'Rumple Minze'},
  { label: 'Anise'},
  { label: 'Yellow Chartreuse'},
  { label: 'Kummel'},
  { label: 'Egg white'},
  { label: 'Guava juice'},
  { label: 'Apricot'},
  { label: 'Whipped cream'},
  { label: 'Allspice'},
  { label: 'Gold tequila'},
  { label: 'Lime juice cordial'},
  { label: 'Passion fruit syrup'},
  { label: 'Cream'},
  { label: 'Cornstarch'},
  { label: 'Blackcurrant cordial'},
  { label: 'Olive Brine'},
  { label: 'Pineapple Syrup'},
  { label: 'Condensed milk'},
  { label: 'Salt'},
  { label: 'Agave Syrup'},
  { label: 'Sherbet'},
  { label: 'Aperol'},
  { label: 'Mint syrup'},
  { label: 'Cumin seed'},
  { label: 'Olive'},
  { label: 'Daiquiri mix'},
  { label: 'Pepsi Cola'},
  { label: 'Cloves'},
  { label: 'Orange peel'},
  { label: 'Peychaud bitters'},
  { label: 'Curacao'},
  { label: 'Blackcurrant squash'},
  { label: 'Cardamom'},
  { label: 'Celery salt'},
  { label: 'Lillet Blanc'},
  { label: 'Limeade'},
  { label: 'Cream of coconut'},
  { label: 'Maraschino cherry'},
  { label: 'Hot chocolate'},
  { label: 'Cherry'},
  { label: 'Licorice root'},
  { label: 'Fresh Lemon Juice'},
  { label: 'Almond flavoring'},
  { label: 'Worcestershire sauce'},
  { label: 'Creme de Mure'},
  { label: 'Vanilla'},
  { label: 'Peppermint extract'},
  { label: 'St. Germain'},
  { label: 'Dr. Pepper'},
  { label: 'Sirup of roses'},
  { label: 'Orange spiral'},
  { label: 'Coconut syrup'},
  { label: 'Asafoetida'},
  { label: 'Lime peel'},
  { label: 'Raspberry syrup'},
  { label: 'Fennel seeds'},
  { label: 'Wormwood'},
  { label: 'Fresh Lime Juice'},
  { label: 'Candy'},
  { label: 'caramel sauce'},
  { label: 'Chocolate milk'},
  { label: 'Melon liqueur'},
  { label: 'Marshmallows'},
  { label: 'Cayenne pepper'},
  { label: 'Oreo cookie'},
  { label: 'Whipping cream'},
  { label: 'chocolate sauce'},
  { label: 'Cherry Grenadine'},
  { label: 'Caramel coloring'},
  { label: 'Pepper'},
  { label: 'Cherries'},
  { label: 'Marjoram leaves'},
  { label: 'Mini-snickers bars'},
  { label: 'Lavender'},
  { label: 'Black pepper'},
  { label: 'Fresca'}
];

export const cocktailNames = [
  { label: "'57 Chevy with a White License Plate"},
  { label: '1-900-FUK-MEUP'},
  { label: '110 in the shade'},
  { label: '151 Florida Bushwacker'},
  { label: '155 Belmont'},
{ label: '24k nightmare'},
{ label: '252'},
{ label: '3 Wise Men'},
{ label: '3-Mile Long Island Iced Tea'},
{ label: '410 Gone'},
{ label: '50/50'},
{ label: '501 Blue'},
{ label: '69 Special'},
{ label: '747'},
{ label: '9 1/2 Weeks'},
{ label: 'A Day at the Beach'},
{ label: 'A Furlong Too Late'},
{ label: "A Gilligan's Island"},
{ label: 'A Night In Old Mandalay'},
{ label: 'A Piece of Ass'},
{ label: 'A Splash of Nash'},
{ label: 'A True Amaretto Sour'},
{ label: 'A midsummernight dream'},
{ label: 'A. J.'},
{ label: 'A.D.M. (After Dinner Mint)'},
{ label: 'A1'},
{ label: 'ABC'},
{ label: 'ACID'},
{ label: 'AT&T'},
{ label: 'Abbey Cocktail'},
{ label: 'Abbey Martini'},
{ label: 'Abilene'},
{ label: 'Absinthe #2'},
{ label: 'Absolut Evergreen'},
{ label: 'Absolut Sex'},
{ label: 'Absolut Stress #2'},
{ label: 'Absolut Summertime'},
{ label: 'Absolut limousine'},
{ label: 'Absolutely Cranberry Smash'},
{ label: 'Absolutely Fabulous'},
{ label: 'Absolutly Screwed Up'},
{ label: 'Acapulco'},
{ label: 'Ace'},
{ label: 'Adam'},
{ label: 'Adam & Eve'},
{ label: 'Adam Bomb'},
{ label: 'Adam Sunrise'},
{ label: 'Addington'},
{ label: 'Addison'},
{ label: 'Addison Special'},
{ label: 'Adios Amigos Cocktail'},
{ label: 'Adonis Cocktail'},
{ label: 'Affair'},
{ label: 'Affinity'},
{ label: 'After Dinner Cocktail'},
{ label: 'After Five'},
{ label: 'After Supper Cocktail'},
{ label: 'After sex'},
{ label: 'Afterglow'},
{ label: 'Afternoon'},
{ label: 'Alabama Slammer'},
{ label: 'Alaska Cocktail'},
{ label: 'Alexander'},
{ label: 'Alfie Cocktail'},
{ label: 'Algonquin'},
{ label: 'Alice Cocktail'},
{ label: 'Alice in Wonderland'},
{ label: 'Allegheny'},
{ label: 'Allies Cocktail'},
{ label: 'Almeria'},
{ label: 'Almond Chocolate Coffee'},
{ label: 'Almond Joy'},
{ label: 'Aloha Fruit punch'},
{ label: 'Amaretto And Cream'},
{ label: 'Amaretto Liqueur'},
{ label: 'Amaretto Mist'},
{ label: 'Amaretto Rose'},
{ label: 'Amaretto Shake'},
{ label: 'Amaretto Sour'},
{ label: 'Amaretto Stinger'},
{ label: 'Amaretto Stone Sour'},
{ label: 'Amaretto Stone Sour #3'},
{ label: 'Amaretto Sunrise'},
{ label: 'Amaretto Sunset'},
{ label: 'Amaretto Sweet & Sour'},
{ label: 'Amaretto Tea'},
{ label: 'Americano'},
{ label: 'Angel Face'},
{ label: 'Angelica Liqueur'},
{ label: 'Apello'},
{ label: 'Apple Berry Smoothie'},
{ label: 'Apple Cider Punch #1'},
{ label: 'Apple Grande'},
{ label: 'Apple Karate'},
{ label: 'Apple Pie with A Crust'},
{ label: 'Apple Slammer'},
{ label: 'Applecar'},
{ label: 'Applejack'},
{ label: 'Apricot Lady'},
{ label: 'Apricot punch'},
{ label: 'Archbishop'},
{ label: 'Arctic Fish'},
{ label: 'Arctic Mouthwash'},
{ label: 'Arise My Love'},
{ label: 'Arizona Antifreeze'},
{ label: 'Arizona Stingers'},
{ label: 'Arizona Twister'},
{ label: 'Army special'},
{ label: 'Arthur Tompkins'},
{ label: 'Artillery'},
{ label: 'Artillery Punch'},
{ label: 'Atlantic Sun'},
{ label: 'Atomic Lokade'},
{ label: 'Auburn Headbanger'},
{ label: 'AutodafÃƒÂ©'},
{ label: 'Avalanche'},
{ label: 'Avalon'},
{ label: 'Aviation'},
{ label: 'Aztec Punch'},
{ label: 'B-52'},
{ label: 'B-53'},
{ label: 'Baby Eskimo'},
{ label: 'Baby Guinness'},
{ label: 'Bacardi Cocktail'},
{ label: "Bailey's Dream Shake"},
{ label: 'Balmoral'},
{ label: 'Banana Cantaloupe Smoothie'},
{ label: 'Banana Daiquiri'},
{ label: 'Banana Milk Shake'},
{ label: 'Banana Strawberry Shake'},
{ label: 'Banana Strawberry Shake Daiquiri-type'},
{ label: 'Barracuda'},
{ label: 'Belgian Blue'},
{ label: 'Bellini'},
{ label: 'Bellini Martini'},
{ label: 'Bermuda Highball'},
{ label: 'Berry Deadly'},
{ label: 'Between The Sheets'},
{ label: 'Bible Belt'},
{ label: 'Big Red'},
{ label: 'Black & Tan'},
{ label: 'Black Forest Shake'},
{ label: 'Black Russian'},
{ label: 'Black and Brown'},
{ label: 'Blackthorn'},
{ label: 'Bleeding Surgeon'},
{ label: 'Blind Russian'},
{ label: 'Bloody Maria'},
{ label: 'Bloody Mary'},
{ label: 'Blue Lagoon'},
{ label: 'Blue Margarita'},
{ label: 'Blue Mountain'},
{ label: 'Bluebird'},
{ label: 'Bob Marley'},
{ label: 'Bobby Burns Cocktail'},
{ label: 'Boomerang'},
{ label: 'Boozy Snickers Milkshake'},
{ label: 'Bora Bora'},
{ label: 'Boston Sidecar'},
{ label: 'Boston Sour'},
{ label: 'Bourbon Sling'},
{ label: 'Bourbon Sour'},
{ label: 'Boxcar'},
{ label: 'Brain Fart'},
{ label: 'Brainteaser'},
{ label: 'Bramble'},
{ label: "Brandon and Will's Coke Float"},
{ label: 'Brandy Alexander'},
{ label: 'Brandy Cobbler'},
{ label: 'Brandy Flip'},
{ label: 'Brandy Sour'},
{ label: 'Brave Bull Shooter'},
{ label: "Bruce's Puce"},
{ label: 'Bruised Heart'},
{ label: 'Bubble Gum'},
{ label: 'Buccaneer'},
{ label: 'Bumble Bee #1'},
{ label: 'Butter Baby'},
{ label: 'Cafe Savoy'},
{ label: 'Caipirinha'},
{ label: 'Caipirissima'},
{ label: 'California Lemonade'},
{ label: 'California Root Beer'},
{ label: 'Campari Beer'},
{ label: 'Caribbean Boilermaker'},
{ label: 'Caribbean Orange Liqueur'},
{ label: 'Casino'},
{ label: 'Casino Royale'},
{ label: 'Castillian Hot Chocolate'},
{ label: 'Champagne Cocktail'},
{ label: 'Cherry Electric Lemonade'},
{ label: 'Cherry Rum'},
{ label: 'Chicago Fizz'},
{ label: 'Chocolate Beverage'},
{ label: 'Chocolate Black Russian'},
{ label: 'Chocolate Drink'},
{ label: 'Chocolate Milk'},
{ label: 'Chocolate Monkey'},
{ label: 'Citrus Coke'},
{ label: 'City Slicker'},
{ label: 'Classic Old-Fashioned'},
{ label: 'Clove Cocktail'},
{ label: 'Clover Club'},
{ label: 'Coffee Liqueur'},
{ label: 'Coffee-Vodka'},
{ label: 'Coke and Drops'},
{ label: 'Cosmopolitan'},
{ label: 'Cosmopolitan Martini'},
{ label: 'Cranberry Cordial'},
{ label: 'Cranberry Punch'},
{ label: 'Cream Soda'},
{ label: 'Creme de Menthe'},
{ label: 'Cuba Libra'},
{ label: 'Cuba Libre'},
{ label: 'Daiquiri'},
{ label: 'Damned if you do'},
{ label: 'Danbooka'},
{ label: 'Dark Caipirinha'},
{ label: 'Dark and Stormy'},
{ label: 'Darkwood Sling'},
{ label: 'Derby'},
{ label: 'Diesel'},
{ label: 'Dirty Martini'},
{ label: 'Dirty Nipple'},
{ label: 'Downshift'},
{ label: 'Dragonfly'},
{ label: 'Drinking Chocolate'},
{ label: 'Dry Rob Roy'},
{ label: 'Dubonnet Cocktail'},
{ label: "Duchamp's Punch"},
{ label: 'Egg Cream'},
{ label: 'Egg Nog #4'},
{ label: 'Egg Nog - Healthy'},
{ label: 'Egg-Nog - Classic Cooked'},
{ label: 'English Highball'},
{ label: 'English Rose Cocktail'},
{ label: 'Espresso Martini'},
{ label: 'Fahrenheit 5000'},
{ label: 'Flaming Dr. Pepper'},
{ label: 'Flaming Lamborghini'},
{ label: "Flander's Flake-Out"},
{ label: 'Flying Dutchman'},
{ label: 'Flying Scotchman'},
{ label: 'Foxy Lady'},
{ label: 'FrappÃƒÂ©'},
{ label: 'Freddy Kruger'},
{ label: 'French "75"'},
{ label: 'French 75'},
{ label: 'French Connection'},
{ label: 'French Martini'},
{ label: 'Frisco Sour'},
{ label: 'Frozen Daiquiri'},
{ label: 'Frozen Mint Daiquiri'},
{ label: 'Frozen Pineapple Daiquiri'},
{ label: 'Fruit Cooler'},
{ label: 'Fruit Flip-Flop'},
{ label: 'Fruit Shake'},
{ label: 'Fuzzy Asshole'},
{ label: 'GG'},
{ label: 'Gagliardo'},
{ label: "Gentleman's Club"},
{ label: "Gideon's Green Dinosaur"},
{ label: 'Gin And Tonic'},
{ label: 'Gin Cooler'},
{ label: 'Gin Daisy'},
{ label: 'Gin Fizz'},
{ label: 'Gin Rickey'},
{ label: 'Gin Sling'},
{ label: 'Gin Smash'},
{ label: 'Gin Sour'},
{ label: 'Gin Squirt'},
{ label: 'Gin Swizzle'},
{ label: 'Gin Toddy'},
{ label: 'Girl From Ipanema'},
{ label: 'Gluehwein'},
{ label: 'Godchild'},
{ label: 'Godfather'},
{ label: 'Godmother'},
{ label: 'Golden dream'},
{ label: 'Grand Blue'},
{ label: 'Grape lemon pineapple Smoothie'},
{ label: 'Grass Skirt'},
{ label: 'Grasshopper'},
{ label: 'Green Goblin'},
{ label: 'Grim Reaper'},
{ label: 'Grizzly Bear'},
{ label: 'H.D.'},
{ label: 'Happy Skipper'},
{ label: 'Harvey Wallbanger'},
{ label: 'Havana Cocktail'},
{ label: 'Hawaiian Cocktail'},
{ label: 'Hemingway Special'},
{ label: 'Herbal flame'},
{ label: 'Highland Fling Cocktail'},
{ label: 'Holloween Punch'},
{ label: 'Homemade Kahlua'},
{ label: "Horse's Neck"},
{ label: 'Hot Chocolate to Die for'},
{ label: 'Hot Creamy Bush'},
{ label: 'Ice Pick #1'},
{ label: 'Iced Coffee'},
{ label: 'Iced Coffee Fillip'},
{ label: 'Imperial Cocktail'},
{ label: 'Imperial Fizz'},
{ label: 'Ipamena'},
{ label: 'Irish Coffee'},
{ label: 'Irish Cream'},
{ label: 'Irish Curdling Cow'},
{ label: 'Irish Russian'},
{ label: 'Irish Spring'},
{ label: 'Jack Rose Cocktail'},
{ label: "Jack's Vanilla Coke"},
{ label: 'Jackhammer'},
{ label: 'Jam Donut'},
{ label: 'Jamaica Kiss'},
{ label: 'Jamaican Coffee'},
{ label: 'Japanese Fizz'},
{ label: 'Jello shots'},
{ label: 'Jelly Bean'},
{ label: 'Jewel Of The Nile'},
{ label: 'Jitterbug'},
{ label: 'John Collins'},
{ label: 'Just a Moonmint'},
{ label: 'Kamikaze'},
{ label: 'Karsk'},
{ label: 'Kentucky B And B'},
{ label: 'Kentucky Colonel'},
{ label: 'Kill the cold Smoothie'},
{ label: 'Kioki Coffee'},
{ label: 'Kir'},
{ label: 'Kir Royale'},
{ label: 'Kiss me Quick'},
{ label: 'Kiwi Lemon'},
{ label: 'Kiwi Papaya Smoothie'},
{ label: 'Kool First Aid'},
{ label: 'Kool-Aid Shot'},
{ label: 'Kool-Aid Slammer'},
{ label: 'Kurant Tea'},
{ label: 'Lady Love Fizz'},
{ label: 'Lassi - A South Indian Drink'},
{ label: 'Lassi - Mango'},
{ label: 'Lassi - Sweet'},
{ label: 'Lassi Khara'},
{ label: 'Lassi Raita'},
{ label: 'Lemon Drop'},
{ label: 'Lemon Shot'},
{ label: 'Lemouroudji'},
{ label: 'Limeade'},
{ label: 'Limona Corona'},
{ label: 'Loch Lomond'},
{ label: 'London Town'},
{ label: 'Lone Tree Cocktail'},
{ label: 'Lone Tree Cooler'},
{ label: 'Long Island Iced Tea'},
{ label: 'Long Island Tea'},
{ label: 'Long vodka'},
{ label: 'Lord And Lady'},
{ label: 'Lunch Box'},
{ label: 'Mai Tai'},
{ label: 'Malibu Twister'},
{ label: 'Mango Orange Smoothie'},
{ label: 'Manhattan'},
{ label: 'Margarita'},
{ label: 'Martinez Cocktail'},
{ label: 'Martini'},
{ label: 'Mary Pickford'},
{ label: 'Masala Chai'},
{ label: 'Melya'},
{ label: 'Miami Vice'},
{ label: 'Microwave Hot Cocoa'},
{ label: 'Midnight Cowboy'},
{ label: 'Midnight Manx'},
{ label: 'Midnight Mint'},
{ label: 'Mimosa'},
{ label: 'Mississippi Planters Punch'},
{ label: 'Mocha-Berry'},
{ label: 'Mojito'},
{ label: 'Mojito #3'},
{ label: 'Monkey Gland'},
{ label: 'Monkey Wrench'},
{ label: 'Moranguito'},
{ label: 'Moscow Mule'},
{ label: "Mother's Milk"},
{ label: 'Mudslinger'},
{ label: 'Mulled Wine'},
{ label: 'National Aquarium'},
{ label: 'Negroni'},
{ label: 'New York Lemonade'},
{ label: 'New York Sour'},
{ label: 'Nuked Hot Chocolate'},
{ label: 'Nutty Irishman'},
{ label: 'Old Fashioned'},
{ label: 'Orange Crush'},
{ label: 'Orange Oasis'},
{ label: 'Orange Push-up'},
{ label: 'Orange Scented Hot Chocolate'},
{ label: 'Orange Whip'},
{ label: 'Orangeade'},
{ label: 'Oreo Mudslide'},
{ label: 'Orgasm'},
{ label: "Owen's Grandmother's Revenge"},
{ label: 'Paradise'},
{ label: 'Pina Colada'},
{ label: 'Pineapple Gingerale Smoothie'},
{ label: 'Pink Gin'},
{ label: 'Pink Lady'},
{ label: 'Pink Panty Pulldowns'},
{ label: 'Pink Penocha'},
{ label: 'Pisco Sour'},
{ label: "Planter's Punch"},
{ label: 'Popped cherry'},
{ label: 'Poppy Cocktail'},
{ label: 'Port And Starboard'},
{ label: 'Port Wine Cocktail'},
{ label: 'Port Wine Flip'},
{ label: 'Porto flip'},
{ label: 'Pysch Vitamin Light'},
{ label: "Quaker's Cocktail"},
{ label: 'Quarter Deck Cocktail'},
{ label: 'Queen Bee'},
{ label: 'Queen Charlotte'},
{ label: 'Queen Elizabeth'},
{ label: 'Quentin'},
{ label: 'Quick F**K'},
{ label: 'Quick-sand'},
{ label: 'Radioactive Long Island Iced Tea'},
{ label: 'Radler'},
{ label: 'Rail Splitter'},
{ label: 'Raspberry Cooler'},
{ label: 'Red Snapper'},
{ label: 'Rose'},
{ label: 'Royal Bitch'},
{ label: 'Royal Fizz'},
{ label: 'Royal Flush'},
{ label: 'Royal Gin Fizz'},
{ label: 'Ruby Tuesday'},
{ label: 'Rum Cobbler'},
{ label: 'Rum Cooler'},
{ label: 'Rum Milk Punch'},
{ label: 'Rum Old-fashioned'},
{ label: 'Rum Punch'},
{ label: 'Rum Runner'},
{ label: 'Rum Screwdriver'},
{ label: 'Rum Sour'},
{ label: 'Rum Toddy'},
{ label: 'Russian Spring Punch'},
{ label: 'Rusty Nail'},
{ label: 'Salty Dog'},
{ label: 'San Francisco'},
{ label: 'Sangria #1'},
{ label: "Sangria - The World's Best"},
{ label: 'Sazerac'},
{ label: 'Scooter'},
{ label: 'Scotch Cobbler'},
{ label: 'Scotch Sour'},
{ label: 'Scottish Highland Liqueur'},
{ label: 'Screaming Orgasm'},
{ label: 'Screwdriver'},
{ label: 'Sea breeze'},
{ label: 'Sex on the Beach'},
{ label: 'Shanghai Cocktail'},
{ label: 'Shark Attack'},
{ label: 'Sherry Eggnog'},
{ label: 'Sherry Flip'},
{ label: 'Shot-gun'},
{ label: 'Sidecar'},
{ label: 'Sidecar Cocktail'},
{ label: 'Singapore Sling'},
{ label: 'Sloe Gin Cocktail'},
{ label: 'Smut'},
{ label: 'Snake Bite (UK)'},
{ label: 'Snakebite and Black'},
{ label: 'Snowball'},
{ label: 'Sol Y Sombra'},
{ label: 'Space Odyssey'},
{ label: 'Spanish chocolate'},
{ label: 'Spiced Peach Punch'},
{ label: 'Spiking coffee'},
{ label: 'Spritz'},
{ label: 'Stinger'},
{ label: 'Stone Sour'},
{ label: 'Strawberry Daiquiri'},
{ label: 'Strawberry Lemonade'},
{ label: 'Strawberry Margarita'},
{ label: 'Strawberry Shivers'},
{ label: 'Sunny Holiday Punch'},
{ label: 'Surf City Lifesaver'},
{ label: 'Swedish Coffee'},
{ label: 'Sweet Bananas'},
{ label: 'Sweet Sangria'},
{ label: 'Sweet Tooth'},
{ label: 'Talos Coffee'},
{ label: 'Tennesee Mud'},
{ label: 'Tequila Fizz'},
{ label: 'Tequila Sour'},
{ label: 'Tequila Sunrise'},
{ label: 'Tequila Surprise'},
{ label: 'Texas Rattlesnake'},
{ label: 'Texas Sling'},
{ label: 'Thai Coffee'},
{ label: 'Thai Iced Coffee'},
{ label: 'Thai Iced Tea'},
{ label: 'The Evil Blue Thing'},
{ label: 'Thriller'},
{ label: 'Tia-Maria'},
{ label: 'Tom Collins'},
{ label: 'Tomato Tang'},
{ label: "Tommy's Margarita"},
{ label: 'Turf Cocktail'},
{ label: 'Turkeyball'},
{ label: 'Tuxedo Cocktail'},
{ label: 'Valencia Cocktail'},
{ label: 'Vampiro'},
{ label: 'Van Vleet'},
{ label: 'Vermouth Cassis'},
{ label: 'Vesper'},
{ label: 'Vesuvio'},
{ label: 'Veteran'},
{ label: 'Victor'},
{ label: 'Victory Collins'},
{ label: 'Vodka And Tonic'},
{ label: 'Vodka Fizz'},
{ label: 'Vodka Martini'},
{ label: 'Vodka Russian'},
{ label: 'Waikiki Beachcomber'},
{ label: 'Whiskey Sour'},
{ label: 'Whisky Mac'},
{ label: 'White Lady'},
{ label: 'White Russian'},
{ label: 'Whitecap Margarita'},
{ label: 'Wine Cooler'},
{ label: 'Wine Punch'},
{ label: 'Yellow Bird'},
{ label: 'Yoghurt Cooler'},
{ label: 'Zambeer'},
{ label: 'Zenmeister'},
{ label: 'Ziemes Martini Apfelsaft'},
{ label: 'Zima Blaster'},
{ label: 'Zimadori Zinger'},
{ label: 'Zinger'},
{ label: 'Zipperhead'},
{ label: 'Zippys Revenge'},
{ label: 'Zizi Coin-coin'},
{ label: 'Zoksel'},
{ label: 'Zorbatini'},
{ label: 'Zorro'}
];

export const glassware = [
  { label: 'Highball glass'},
  { label: 'Old-fashioned glass'},
  { label: 'Beer Glass'},
  { label: 'Beer mug'},
  { label: 'White wine glass'},
{ label: 'Shot glass'},
{ label: 'Collins glass'},
{ label: 'Cocktail glass'},
{ label: 'Irish coffee cup'},
{ label: 'Jar'},
{ label: 'Champagne flute'},
{ label: 'Martini Glass'},
{ label: 'Margarita/Coupette glass'},
{ label: 'Coffee mug'},
{ label: 'Pousse cafe glass'},
{ label: 'Punch Bowl'},
{ label: 'Beer pilsner'},
{ label: 'Hurricane glass'},
{ label: 'Whiskey sour glass'},
{ label: 'Margarita glass'},
{ label: 'Pint glass'},
{ label: 'Mason jar'},
{ label: 'Parfait glass'},
{ label: 'Pitcher'},
{ label: 'Wine Glass'},
{ label: 'Cordial glass'},
{ label: 'Brandy snifter'},
{ label: 'Copper Mug'}
];